# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.integration_blueprint: debug
  filters:
    homeassistant.components.go2rtc:
      - "Could not find go2rtc docker binary"
    homeassistant.setup:
      - ".*go2rtc.*"